export const COMMUNITY_POST_TOKENS = {
  COMMUNITY_POST_REPOSITORY: Symbol('COMMUNITY_POST_REPOSITORY'),
  COMMUNITY_POST_ENGAGEMENT_REPOSITORY: Symbol(
    'COMMUNITY_POST_ENGAGEMENT_REPOSITORY',
  ),
} as const;
