export enum StudentPortalAccessReason {
  ACCESS_GRANTED = 'ACCESS_GRANTED',
  STUDENT_PROFILE_NOT_FOUND = 'STUDENT_PROFILE_NOT_FOUND',
  NO_ENROLLMENT = 'NO_ENROLLMENT',
  STUDENT_NOT_ADMITTED = 'STUDENT_NOT_ADMITTED',
  ENROLLMENT_NOT_ADMITTED = 'ENROLLMENT_NOT_ADMITTED',
}
