export enum JobApplicationInterviewStatus {
  NOT_YET = 'NOT_YET',
  INTERVIEW_SCHEDULED = 'INTERVIEW_SCHEDULED',
  INTERVIEWED = 'INTERVIEWED',
  SELECTED = 'SELECTED',
  REJECTED = 'REJECTED',
  PLACED = 'PLACED',
}
