// src/common/constants/error-codes.ts

export const ERROR_CODES = {
  // COMMON
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
  UNAUTHORIZED: 'UNAUTHORIZED',

  // USER
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  USER_ALREADY_EXISTS: 'USER_ALREADY_EXISTS',

  // PROFILE
  PROFILE_NOT_FOUND: 'PROFILE_NOT_FOUND',

  // BRANCH
  BRANCH_NOT_FOUND: 'BRANCH_NOT_FOUND',
  BRANCH_ALREADY_EXISTS: 'BRANCH_ALREADY_EXISTS',
  BRANCH_INACTIVE: 'BRANCH_INACTIVE',
  BRANCH_DELETED: 'BRANCH_DELETED',

  // BRANCH USER
  BRANCH_USER_NOT_FOUND: 'BRANCH_USER_NOT_FOUND',
  BRANCH_USER_ALREADY_EXISTS: 'BRANCH_USER_ALREADY_EXISTS',
  BRANCH_USER_INACTIVE: 'BRANCH_USER_INACTIVE',
  BRANCH_USER_DELETED: 'BRANCH_USER_DELETED',
  BRANCH_ACCESS_DENIED: 'BRANCH_ACCESS_DENIED',
  PERMISSION_DENIED: 'PERMISSION_DENIED',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  INVALID_TOKEN: 'INVALID_TOKEN',
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',

  // FILE STORAGE - removed (use UPLOAD_* codes)

  // UPLOADS
  UPLOAD_NOT_FOUND: 'UPLOAD_NOT_FOUND',
  INVALID_FILE: 'INVALID_FILE',
  FILE_TOO_LARGE: 'FILE_TOO_LARGE',
  S3_UPLOAD_FAILED: 'S3_UPLOAD_FAILED',
  S3_DELETE_FAILED: 'S3_DELETE_FAILED',
  UNSUPPORTED_MIME_TYPE: 'UNSUPPORTED_MIME_TYPE',
  FILE_ALREADY_DELETED: 'FILE_ALREADY_DELETED',
  S3_COPY_FAILED: 'S3_COPY_FAILED',
  S3_OBJECT_NOT_FOUND: 'S3_OBJECT_NOT_FOUND',

  // CATEGORY
  CATEGORY_NOT_FOUND: 'CATEGORY_NOT_FOUND',
  CATEGORY_ALREADY_EXISTS: 'CATEGORY_ALREADY_EXISTS',
  CATEGORY_INACTIVE: 'CATEGORY_INACTIVE',
  CATEGORY_DELETED: 'CATEGORY_DELETED',
  CATEGORY_BRANCH_MISMATCH: 'CATEGORY_BRANCH_MISMATCH',

  // COURSE
  COURSE_NOT_FOUND: 'COURSE_NOT_FOUND',
  COURSE_ALREADY_EXISTS: 'COURSE_ALREADY_EXISTS',
  INVALID_COURSE_PRICING: 'INVALID_COURSE_PRICING',
  COURSE_INACTIVE: 'COURSE_INACTIVE',
  COURSE_DELETED: 'COURSE_DELETED',
  COURSE_IN_DRAFT: 'COURSE_IN_DRAFT',
  COURSE_ARCHIVED: 'COURSE_ARCHIVED',
  COURSE_NOT_AVAILABLE: 'COURSE_NOT_AVAILABLE',
  COURSE_CATEGORY_MISMATCH: 'COURSE_CATEGORY_MISMATCH',

  // TRAINER
  TRAINER_NOT_FOUND: 'TRAINER_NOT_FOUND',
  TRAINER_ALREADY_EXISTS: 'TRAINER_ALREADY_EXISTS',

  // BATCH
  BATCH_NOT_FOUND: 'BATCH_NOT_FOUND',
  BATCH_ALREADY_EXISTS: 'BATCH_ALREADY_EXISTS',
  BATCH_FULL: 'BATCH_FULL',
  BATCH_INACTIVE: 'BATCH_INACTIVE',
  BATCH_DELETED: 'BATCH_DELETED',
  BATCH_COMPLETED: 'BATCH_COMPLETED',
  BATCH_CANCELLED: 'BATCH_CANCELLED',
  BATCH_ALREADY_STARTED: 'BATCH_ALREADY_STARTED',
  BATCH_COURSE_MISMATCH: 'BATCH_COURSE_MISMATCH',

  // STUDENT
  STUDENT_NOT_FOUND: 'STUDENT_NOT_FOUND',
  STUDENT_ALREADY_EXISTS: 'STUDENT_ALREADY_EXISTS',
  STUDENT_INACTIVE: 'STUDENT_INACTIVE',
  STUDENT_DELETED: 'STUDENT_DELETED',
  STUDENT_ALREADY_ENROLLED: 'STUDENT_ALREADY_ENROLLED',
  STUDENT_BRANCH_MISMATCH: 'STUDENT_BRANCH_MISMATCH',
  STUDENT_DETAILS_REQUIRED: 'STUDENT_DETAILS_REQUIRED',
  STUDENT_DOCUMENT_NOT_FOUND: 'STUDENT_DOCUMENT_NOT_FOUND',

  // ENROLLMENT
  ENROLLMENT_NOT_FOUND: 'ENROLLMENT_NOT_FOUND',
  ENROLLMENT_ALREADY_EXISTS: 'ENROLLMENT_ALREADY_EXISTS',
  ENROLLMENT_DELETED: 'ENROLLMENT_DELETED',
  ENROLLMENT_NOT_DELETED: 'ENROLLMENT_NOT_DELETED',
  ENROLLMENT_NOT_PENDING_APPROVAL: 'ENROLLMENT_NOT_PENDING_APPROVAL',
  ENROLLMENT_PAYMENT_NOT_VERIFIED: 'ENROLLMENT_PAYMENT_NOT_VERIFIED',
  INVALID_DISCOUNT: 'INVALID_DISCOUNT',
  INVALID_PAYMENT_AMOUNT: 'INVALID_PAYMENT_AMOUNT',
  INVALID_STATUS_TRANSITION: 'INVALID_STATUS_TRANSITION',
  RESTORE_BATCH_FULL: 'RESTORE_BATCH_FULL',
  INVALID_ENROLLMENT_NUMBER: 'INVALID_ENROLLMENT_NUMBER',

  // PAYMENT
  PAYMENT_NOT_FOUND: 'PAYMENT_NOT_FOUND',
  PAYMENT_ALREADY_EXISTS: 'PAYMENT_ALREADY_EXISTS',
  PAYMENT_DELETED: 'PAYMENT_DELETED',
  PAYMENT_NOT_DELETED: 'PAYMENT_NOT_DELETED',
  PAYMENT_ACCESS_DENIED: 'PAYMENT_ACCESS_DENIED',
  PAYMENT_ALREADY_PROCESSED: 'PAYMENT_ALREADY_PROCESSED',
  PAYMENT_NOT_REFUNDABLE: 'PAYMENT_NOT_REFUNDABLE',
  INVALID_PAYMENT_STATUS_TRANSITION: 'INVALID_PAYMENT_STATUS_TRANSITION',
  INVALID_PAYMENT_NUMBER: 'INVALID_PAYMENT_NUMBER',
  INVALID_PAYMENT_METHOD: 'INVALID_PAYMENT_METHOD',
  ENROLLMENT_ALREADY_PAID: 'ENROLLMENT_ALREADY_PAID',
  PAYMENT_AMOUNT_EXCEEDS_DUE: 'PAYMENT_AMOUNT_EXCEEDS_DUE',
  PAYMENT_GATEWAY_ERROR: 'PAYMENT_GATEWAY_ERROR',
  PAYMENT_GATEWAY_NOT_CONFIGURED: 'PAYMENT_GATEWAY_NOT_CONFIGURED',
  INVALID_PAYMENT_SIGNATURE: 'INVALID_PAYMENT_SIGNATURE',
  INVALID_WEBHOOK_SIGNATURE: 'INVALID_WEBHOOK_SIGNATURE',

  // COURSE MODULE / LESSON / RESOURCE
  COURSE_MODULE_NOT_FOUND: 'COURSE_MODULE_NOT_FOUND',
  COURSE_LESSON_NOT_FOUND: 'COURSE_LESSON_NOT_FOUND',
  COURSE_RESOURCE_NOT_FOUND: 'COURSE_RESOURCE_NOT_FOUND',
  COURSE_MODULE_ALREADY_EXISTS: 'COURSE_MODULE_ALREADY_EXISTS',
  COURSE_LESSON_ALREADY_EXISTS: 'COURSE_LESSON_ALREADY_EXISTS',
  INVALID_DISPLAY_ORDER: 'INVALID_DISPLAY_ORDER',
  INVALID_MOVE_POSITION: 'INVALID_MOVE_POSITION',
  COURSE_MODULE_DELETED: 'COURSE_MODULE_DELETED',
  COURSE_LESSON_DELETED: 'COURSE_LESSON_DELETED',
  COURSE_RESOURCE_DELETED: 'COURSE_RESOURCE_DELETED',
  COURSE_QUIZ_NOT_FOUND: 'COURSE_QUIZ_NOT_FOUND',
  COURSE_QUIZ_ALREADY_EXISTS: 'COURSE_QUIZ_ALREADY_EXISTS',
  COURSE_QUIZ_DELETED: 'COURSE_QUIZ_DELETED',
  COURSE_QUIZ_QUESTION_NOT_FOUND: 'COURSE_QUIZ_QUESTION_NOT_FOUND',
  COURSE_QUIZ_NOT_PUBLISHABLE: 'COURSE_QUIZ_NOT_PUBLISHABLE',

  // STUDENT PORTAL
  STUDENT_PORTAL_ACCESS_DENIED: 'STUDENT_PORTAL_ACCESS_DENIED',
  STUDENT_PORTAL_STUDENT_NOT_FOUND: 'STUDENT_PORTAL_STUDENT_NOT_FOUND',
  STUDENT_PORTAL_ENROLLMENT_NOT_FOUND: 'STUDENT_PORTAL_ENROLLMENT_NOT_FOUND',
  STUDENT_PORTAL_STUDENT_NOT_ADMITTED: 'STUDENT_PORTAL_STUDENT_NOT_ADMITTED',
  STUDENT_PORTAL_ENROLLMENT_NOT_ADMITTED:
    'STUDENT_PORTAL_ENROLLMENT_NOT_ADMITTED',

  // COURSE ACCESS
  COURSE_ACCESS_DENIED: 'COURSE_ACCESS_DENIED',
  COURSE_LESSON_NOT_PREVIEW: 'COURSE_LESSON_NOT_PREVIEW',

  // JOB
  JOB_NOT_FOUND: 'JOB_NOT_FOUND',
  JOB_ALREADY_EXISTS: 'JOB_ALREADY_EXISTS',
  JOB_INACTIVE: 'JOB_INACTIVE',
  JOB_CLOSED: 'JOB_CLOSED',
  JOB_DELETED: 'JOB_DELETED',
  JOB_EXPIRED: 'JOB_EXPIRED',
  JOB_HAS_APPLICATIONS: 'JOB_HAS_APPLICATIONS',

  // JOB APPLICATION
  JOB_APPLICATION_NOT_FOUND: 'JOB_APPLICATION_NOT_FOUND',
  JOB_ALREADY_APPLIED: 'JOB_ALREADY_APPLIED',
  STUDENT_NOT_ADMITTED: 'STUDENT_NOT_ADMITTED',
  INVALID_APPLICATION_STATUS_TRANSITION:
    'INVALID_APPLICATION_STATUS_TRANSITION',
  JOB_APPLICATION_DELETED: 'JOB_APPLICATION_DELETED',
  JOB_APPLICATION_NOT_DELETED: 'JOB_APPLICATION_NOT_DELETED',

  // PLACEMENT
  PLACEMENT_NOT_FOUND: 'PLACEMENT_NOT_FOUND',
  PLACEMENT_ALREADY_EXISTS: 'PLACEMENT_ALREADY_EXISTS',

  // FINANCIAL ARTICLE
  FINANCIAL_ARTICLE_NOT_FOUND: 'FINANCIAL_ARTICLE_NOT_FOUND',
  FINANCIAL_ARTICLE_ALREADY_EXISTS: 'FINANCIAL_ARTICLE_ALREADY_EXISTS',
  FINANCIAL_ARTICLE_DELETED: 'FINANCIAL_ARTICLE_DELETED',
  FINANCIAL_ARTICLE_INACTIVE: 'FINANCIAL_ARTICLE_INACTIVE',

  // COMMUNITY POST
  POST_NOT_FOUND: 'POST_NOT_FOUND',
  POST_ALREADY_EXISTS: 'POST_ALREADY_EXISTS',
  POST_ALREADY_LIKED: 'POST_ALREADY_LIKED',
  POST_NOT_LIKED: 'POST_NOT_LIKED',
  POST_INACTIVE: 'POST_INACTIVE',
  POST_ARCHIVED: 'POST_ARCHIVED',
  POST_DELETED: 'POST_DELETED',
  POST_NOT_DELETED: 'POST_NOT_DELETED',

  // COMMUNITY COMMENT
  COMMENT_NOT_FOUND: 'COMMENT_NOT_FOUND',
  COMMENT_ACCESS_DENIED: 'COMMENT_ACCESS_DENIED',
  COMMENT_BLOCKED: 'COMMENT_BLOCKED',
  COMMENT_DELETED: 'COMMENT_DELETED',
  COMMENT_NOT_DELETED: 'COMMENT_NOT_DELETED',
  INVALID_REPLY_TARGET: 'INVALID_REPLY_TARGET',
} as const;

export type ErrorCode =
  (typeof ERROR_CODES)[keyof typeof ERROR_CODES];