// domain/enums/audit-action.enum.ts
export enum AuditAction {
  REGISTER = 'REGISTER',
  LOGIN = 'LOGIN',
  LOGIN_FAILED = 'LOGIN_FAILED',
  LOGOUT = 'LOGOUT',
  LOGOUT_ALL = 'LOGOUT_ALL',
  REFRESH = 'REFRESH',
  SESSION_REVOKED = 'SESSION_REVOKED',

  // 🔥 NEW (password reset tracking)
  PASSWORD_RESET_REQUESTED = 'PASSWORD_RESET_REQUESTED',
  PASSWORD_RESET_SUCCESS = 'PASSWORD_RESET_SUCCESS',
  PASSWORD_RESET_FAILED = 'PASSWORD_RESET_FAILED',

  // 🔐 MFA
  MFA_REQUESTED = 'MFA_REQUESTED',
  MFA_SUCCESS = 'MFA_SUCCESS',
  MFA_FAILED = 'MFA_FAILED',

  ADMIN_LOGIN = 'ADMIN_LOGIN',
  ADMIN_LOGIN_FAILED = 'ADMIN_LOGIN_FAILED',
  ADMIN_LOGOUT = 'ADMIN_LOGOUT',
  ADMIN_MFA_SUCCESS = 'ADMIN_MFA_SUCCESS',
  ADMIN_MFA_FAILED = 'ADMIN_MFA_FAILED',
}
