export const AUTH_TOKENS = {
  USER_REPOSITORY: 'USER_REPOSITORY',
  SESSION_REPOSITORY: 'SESSION_REPOSITORY',
  AUDIT_LOG_REPOSITORY: 'AUDIT_LOG_REPOSITORY',
  TOKEN_PORT: 'TOKEN_PORT',
  PASSWORD_RESET_REPOSITORY: 'PASSWORD_RESET_REPOSITORY',
};