import {
  generateMetaDescription,
  generateMetaKeywords,
  generateMetaTitle,
  isAutoGeneratedValue,
} from "@/src/features/courses/utils/course-meta.utils";

export interface FinanceNewsMetaSource {
  title?: string;
  shortDescription?: string;
  content?: string;
  tags?: string[];
}

export interface GeneratedFinanceNewsMeta {
  metaTitle: string;
  metaDescription: string;
  metaKeywords: string;
}

export function generateFinanceNewsMeta(
  source: FinanceNewsMetaSource,
): GeneratedFinanceNewsMeta {
  const title = source.title?.trim() ?? "";

  const keywordBase = generateMetaKeywords({
    title: source.title,
    shortDescription: source.shortDescription,
    description: source.content,
  });

  const tagKeywords = (source.tags ?? [])
    .map((tag) => tag.trim().toLowerCase())
    .filter(Boolean)
    .join(", ");

  const metaKeywords = [keywordBase, tagKeywords]
    .filter(Boolean)
    .join(", ")
    .slice(0, 500);

  return {
    metaTitle: generateMetaTitle(title),
    metaDescription: generateMetaDescription({
      shortDescription: source.shortDescription,
      description: source.content,
    }),
    metaKeywords,
  };
}

export { isAutoGeneratedValue };
