export enum WorkingDays {
  ONE_DAY = 'ONE_DAY',
  TWO_DAYS = 'TWO_DAYS',
  THREE_DAYS = 'THREE_DAYS',
  FOUR_DAYS = 'FOUR_DAYS',
  FIVE_DAYS = 'FIVE_DAYS',
  SIX_DAYS = 'SIX_DAYS',
  MONDAY_TO_FRIDAY = 'MONDAY_TO_FRIDAY',
  MONDAY_TO_SATURDAY = 'MONDAY_TO_SATURDAY',
}
