export enum BranchUserRole {
  BRANCH_MANAGER = 'BRANCH_MANAGER',
  RECEPTIONIST = 'RECEPTIONIST',
  ACCOUNTANT = 'ACCOUNTANT',
  FACULTY_COORDINATOR = 'FACULTY_COORDINATOR',
  COUNSELOR = 'COUNSELOR',
  STAFF = 'STAFF',
  FACULTY = 'FACULTY',
  INTERVIEWER = 'INTERVIEWER',
}
