"use client";

import { useCallback, useEffect, useRef, useState } from "react";

import { Controller, useForm } from "react-hook-form";
import { zodResolver } from "@hookform/resolvers/zod";

import { Input } from "@/src/shared/components/ui/input";
import { Textarea } from "@/src/shared/components/ui/textarea";
import { Button } from "@/src/shared/components/ui/button";
import { AppSelect } from "@/src/shared/components/ui/select";
import { WordCount } from "@/src/shared/components/ui/word-count";
import { ImageUploadField } from "@/src/shared/components/ui/image-upload-field";
import {
  ValidatedField,
  validatedFieldInputClass,
} from "@/src/shared/components/ui/validated-field";
import { truncateToMaxWords } from "@/src/shared/utils/word-count";

import {
  COURSE_DURATION_TYPES,
  COURSE_LEVELS,
  COURSE_MODES,
} from "@/src/features/courses/constants/course.constants";
import {
  createCourseSchema,
  CreateCourseFormValues,
} from "@/src/features/courses/schemas/course.schema";
import {
  COURSE_WORD_LIMITS,
  getSyncFieldState,
  getWordCountState,
  validateCourseImageFile,
} from "@/src/features/courses/utils/course-form-validation";
import {
  generateCourseMeta,
  isAutoGeneratedValue,
  type CourseMetaSource,
} from "@/src/features/courses/utils/course-meta.utils";
import { CourseMetaField } from "@/src/features/courses/components/course-meta-field";
import { buildCoursePricingInput } from "@/src/features/courses/utils/course-pricing.util";

interface SelectOption {
  label: string;
  value: string;
}

interface Props {
  courseCode?: string | null;
  defaultValues?: Partial<CreateCourseFormValues> & {
    thumbnailUrl?: string | null;
    status?: string;
  };
  categoryOptions: SelectOption[];
  isEdit?: boolean;
  isLoading?: boolean;
  isUploadingImage?: boolean;
  submitLabel?: string;
  loadingLabel?: string;
  onSubmit: (
    values: CreateCourseFormValues,
    image: File | null,
    removeImage: boolean,
  ) => Promise<void>;
  onCancel?: () => void;
}

const defaultFormValues: CreateCourseFormValues = {
  title: "",
  tagline: "",
  shortDescription: "",
  description: "",
  categoryId: "",
  originalPrice: 0,
  discountPercent: 0,
  discountAmount: 0,
  currency: "INR",
  isFree: false,
  duration: 1,
  durationType: "MONTHS",
  level: "BEGINNER",
  modes: ["ONLINE"],
  language: "English",
  displayOrder: 0,
  slug: "",
  metaTitle: "",
  metaDescription: "",
  metaKeywords: "",
};

const PRICING_TYPE_OPTIONS = [
  { label: "Paid", value: "PAID" },
  { label: "Free", value: "FREE" },
];

const GRID_CLASS = "grid min-w-0 grid-cols-1 gap-4 md:grid-cols-2";
const CELL_CLASS = "min-w-0";

type MetaFieldKey = "metaTitle" | "metaDescription" | "slug" | "metaKeywords";

function formatLevelLabel(level: string) {
  return level.charAt(0) + level.slice(1).toLowerCase();
}

function inputClass(state: ReturnType<typeof getSyncFieldState>) {
  return validatedFieldInputClass(state, "w-full min-w-0 max-w-full");
}

export function CourseForm({
  courseCode,
  defaultValues,
  categoryOptions,
  isEdit = false,
  isLoading = false,
  isUploadingImage = false,
  submitLabel = "Create Course",
  loadingLabel = "Creating Course...",
  onSubmit,
  onCancel,
}: Props) {
  const formRef = useRef<HTMLFormElement | null>(null);
  const [selectedImage, setSelectedImage] = useState<File | null>(null);
  const [removeImage, setRemoveImage] = useState(false);
  const [imageError, setImageError] = useState<string | null>(null);
  const [imageTouched, setImageTouched] = useState(false);
  const [editValidationReady, setEditValidationReady] = useState(false);
  const [metaAutoVersion, setMetaAutoVersion] = useState(0);

  const metaAutoRef = useRef<Record<MetaFieldKey, boolean>>({
    metaTitle: true,
    metaDescription: true,
    slug: true,
    metaKeywords: true,
  });

  const {
    register,
    control,
    watch,
    handleSubmit,
    reset,
    trigger,
    setValue,
    setFocus,
    formState: { errors, touchedFields, isSubmitted },
  } = useForm<CreateCourseFormValues>({
    resolver: zodResolver(createCourseSchema) as never,
    mode: "onTouched",
    reValidateMode: "onChange",
    defaultValues: {
      ...defaultFormValues,
      ...defaultValues,
    },
  });

  const titleValue = watch("title");
  const taglineValue = watch("tagline");
  const shortDescriptionValue = watch("shortDescription");
  const descriptionValue = watch("description");
  const categoryIdValue = watch("categoryId");
  const durationValue = watch("duration");
  const durationTypeValue = watch("durationType");
  const modesValue = watch("modes");
  const levelValue = watch("level");
  const languageValue = watch("language");
  const isFreeValue = watch("isFree");
  const originalPriceValue = watch("originalPrice");
  const discountPercentValue = watch("discountPercent");
  const discountAmountValue = watch("discountAmount");
  const metaTitleValue = watch("metaTitle");
  const metaDescriptionValue = watch("metaDescription");
  const metaKeywordsValue = watch("metaKeywords");
  const slugValue = watch("slug");

  const showValidation = Boolean(isSubmitted || editValidationReady);
  const pricesDisabled = Boolean(isFreeValue);

  const getMetaSource = useCallback((): CourseMetaSource => {
    const categoryName = categoryOptions.find(
      (option) => option.value === categoryIdValue,
    )?.label;

    return {
      title: titleValue,
      tagline: taglineValue,
      shortDescription: shortDescriptionValue,
      description: descriptionValue,
      categoryName,
      level: levelValue,
    };
  }, [
    categoryIdValue,
    categoryOptions,
    descriptionValue,
    levelValue,
    shortDescriptionValue,
    taglineValue,
    titleValue,
  ]);

  const syncMetaAutoFlags = useCallback(
    (values?: Partial<CreateCourseFormValues>) => {
      const source: CourseMetaSource = {
        title: values?.title ?? "",
        tagline: values?.tagline ?? "",
        shortDescription: values?.shortDescription ?? "",
        description: values?.description ?? "",
        categoryName: categoryOptions.find(
          (option) => option.value === values?.categoryId,
        )?.label,
        level: values?.level,
      };
      const generated = generateCourseMeta(source);

      metaAutoRef.current = {
        metaTitle: isAutoGeneratedValue(values?.metaTitle, generated.metaTitle),
        metaDescription: isAutoGeneratedValue(
          values?.metaDescription,
          generated.metaDescription,
        ),
        slug: isAutoGeneratedValue(values?.slug, generated.slug),
        metaKeywords: isAutoGeneratedValue(
          values?.metaKeywords,
          generated.metaKeywords,
        ),
      };
      setMetaAutoVersion((version) => version + 1);
    },
    [categoryOptions],
  );

  useEffect(() => {
    if (!isEdit) {
      setEditValidationReady(false);
      return;
    }

    void trigger().then(() => {
      setEditValidationReady(true);
    });
  }, [isEdit, trigger]);

  useEffect(() => {
    const merged = {
      ...defaultFormValues,
      ...defaultValues,
    };

    reset(merged);
    setSelectedImage(null);
    setRemoveImage(false);
    setImageError(null);
    setImageTouched(false);
    setEditValidationReady(false);

    if (isEdit && defaultValues) {
      syncMetaAutoFlags(merged);
    } else {
      metaAutoRef.current = {
        metaTitle: true,
        metaDescription: true,
        slug: true,
        metaKeywords: true,
      };
      setMetaAutoVersion((version) => version + 1);
    }
  }, [defaultValues, isEdit, reset, syncMetaAutoFlags]);

  useEffect(() => {
    const generated = generateCourseMeta(getMetaSource());

    if (metaAutoRef.current.metaTitle) {
      setValue("metaTitle", generated.metaTitle, {
        shouldValidate: showValidation,
      });
    }

    if (metaAutoRef.current.metaDescription) {
      setValue("metaDescription", generated.metaDescription, {
        shouldValidate: showValidation,
      });
    }

    if (metaAutoRef.current.slug) {
      setValue("slug", generated.slug, {
        shouldValidate: showValidation,
      });
    }

    if (metaAutoRef.current.metaKeywords) {
      setValue("metaKeywords", generated.metaKeywords, {
        shouldValidate: showValidation,
      });
    }
  }, [
    getMetaSource,
    setValue,
    showValidation,
    titleValue,
    taglineValue,
    shortDescriptionValue,
    descriptionValue,
    categoryIdValue,
    levelValue,
  ]);

  const markMetaManual = (field: MetaFieldKey) => {
    metaAutoRef.current[field] = false;
    setMetaAutoVersion((version) => version + 1);
  };

  const resetMetaField = (field: MetaFieldKey) => {
    const generated = generateCourseMeta(getMetaSource());
    const valueMap: Record<MetaFieldKey, string> = {
      metaTitle: generated.metaTitle,
      metaDescription: generated.metaDescription,
      slug: generated.slug,
      metaKeywords: generated.metaKeywords,
    };

    metaAutoRef.current[field] = true;
    setValue(field, valueMap[field], {
      shouldDirty: true,
      shouldValidate: true,
    });
    setMetaAutoVersion((version) => version + 1);
  };

  const isMetaAuto = (field: MetaFieldKey) => {
    void metaAutoVersion;
    return metaAutoRef.current[field];
  };

  const codeState = courseCode ? "valid" : "neutral";

  const titleState = getSyncFieldState(
    Boolean(touchedFields.title || showValidation),
    errors.title?.message,
    titleValue,
    { required: true },
  );

  const taglineState = getSyncFieldState(
    Boolean(touchedFields.tagline || showValidation),
    errors.tagline?.message,
    taglineValue,
  );

  const shortDescriptionState = getWordCountState(
    Boolean(touchedFields.shortDescription || showValidation),
    errors.shortDescription?.message,
    shortDescriptionValue,
    COURSE_WORD_LIMITS.shortDescription,
  );

  const descriptionState = getWordCountState(
    Boolean(touchedFields.description || showValidation),
    errors.description?.message,
    descriptionValue,
    COURSE_WORD_LIMITS.description,
  );

  const categoryState = getSyncFieldState(
    Boolean(touchedFields.categoryId || showValidation),
    errors.categoryId?.message,
    categoryIdValue,
    { required: true },
  );

  const durationState = getSyncFieldState(
    Boolean(touchedFields.duration || showValidation),
    errors.duration?.message,
    durationValue != null ? String(durationValue) : "",
    { required: true },
  );

  const durationTypeState = getSyncFieldState(
    Boolean(touchedFields.durationType || showValidation),
    errors.durationType?.message,
    durationTypeValue,
    { required: true },
  );

  const modeState = getSyncFieldState(
    Boolean(touchedFields.modes || showValidation),
    errors.modes?.message,
    modesValue?.[0],
    { required: true },
  );

  const levelState = getSyncFieldState(
    Boolean(touchedFields.level || showValidation),
    errors.level?.message,
    levelValue,
    { required: true },
  );

  const languageState = getSyncFieldState(
    Boolean(touchedFields.language || showValidation),
    errors.language?.message,
    languageValue,
    { required: true },
  );

  const pricingTypeState = getSyncFieldState(
    Boolean(touchedFields.isFree || showValidation),
    errors.isFree?.message,
    isFreeValue != null ? (isFreeValue ? "FREE" : "PAID") : "",
    { required: true },
  );

  const originalPriceState = getSyncFieldState(
    Boolean(touchedFields.originalPrice || showValidation),
    errors.originalPrice?.message,
    originalPriceValue != null ? String(originalPriceValue) : "",
    { required: !pricesDisabled },
  );

  const discountPercentState = getSyncFieldState(
    Boolean(touchedFields.discountPercent || showValidation),
    errors.discountPercent?.message,
    discountPercentValue != null ? String(discountPercentValue) : "",
    { required: !pricesDisabled },
  );

  const discountAmountState = getSyncFieldState(
    Boolean(touchedFields.discountAmount || showValidation),
    errors.discountAmount?.message,
    discountAmountValue != null ? String(discountAmountValue) : "",
    { required: !pricesDisabled },
  );

  const computedPricing = buildCoursePricingInput({
    originalPrice: Number(originalPriceValue) || 0,
    discountAmount: Number(discountAmountValue) || 0,
    discountPercent: Number(discountPercentValue) || 0,
    currency: watch("currency"),
    isFree: Boolean(isFreeValue),
  });

  const metaTitleState = getSyncFieldState(
    Boolean(touchedFields.metaTitle || showValidation),
    errors.metaTitle?.message,
    metaTitleValue,
  );

  const metaDescriptionState = getSyncFieldState(
    Boolean(touchedFields.metaDescription || showValidation),
    errors.metaDescription?.message,
    metaDescriptionValue,
  );

  const metaKeywordsState = getSyncFieldState(
    Boolean(touchedFields.metaKeywords || showValidation),
    errors.metaKeywords?.message,
    metaKeywordsValue,
  );

  const slugState = getSyncFieldState(
    Boolean(touchedFields.slug || showValidation),
    errors.slug?.message,
    slugValue,
  );

  const durationGroupState =
    durationState === "invalid" || durationTypeState === "invalid"
      ? "invalid"
      : durationState === "valid" && durationTypeState === "valid"
        ? "valid"
        : durationState === "neutral" && durationTypeState === "neutral"
          ? "neutral"
          : durationState === "valid" || durationTypeState === "valid"
            ? "valid"
            : "neutral";

  const durationGroupError =
    errors.duration?.message ?? errors.durationType?.message;

  const imageState =
    imageError ||
    (imageTouched &&
      !selectedImage &&
      !defaultValues?.thumbnailUrl &&
      removeImage)
      ? "invalid"
      : selectedImage || (defaultValues?.thumbnailUrl && !removeImage)
        ? "valid"
        : "neutral";

  const focusFirstInvalidField = () => {
    const fieldOrder: (keyof CreateCourseFormValues)[] = [
      "title",
      "tagline",
      "shortDescription",
      "description",
      "categoryId",
      "modes",
      "duration",
      "durationType",
      "level",
      "language",
      "isFree",
      "originalPrice",
      "discountPercent",
      "discountAmount",
      "metaTitle",
      "metaDescription",
      "slug",
      "metaKeywords",
    ];

    for (const field of fieldOrder) {
      if (errors[field]) {
        setFocus(field);
        return;
      }
    }
  };

  const handleImageSelect = (file: File | null) => {
    setImageTouched(true);

    if (!file) {
      setSelectedImage(null);
      return;
    }

    const validationMessage = validateCourseImageFile(file);

    if (validationMessage) {
      setImageError(validationMessage);
      setSelectedImage(null);
      return;
    }

    setImageError(null);
    setSelectedImage(file);
    setRemoveImage(false);
  };

  const handlePricingTypeChange = (value: string) => {
    const isFree = value === "FREE";
    setValue("isFree", isFree, {
      shouldDirty: true,
      shouldTouch: true,
      shouldValidate: true,
    });

    if (isFree) {
      setValue("originalPrice", 0, {
        shouldDirty: true,
        shouldValidate: true,
      });
      setValue("discountPercent", 0, {
        shouldDirty: true,
        shouldValidate: true,
      });
      setValue("discountAmount", 0, {
        shouldDirty: true,
        shouldValidate: true,
      });
    }
  };

  const metaTitleRegister = register("metaTitle");
  const metaDescriptionRegister = register("metaDescription");
  const metaKeywordsRegister = register("metaKeywords");
  const slugRegister = register("slug");

  return (
    <form
      ref={formRef}
      className="min-w-0 space-y-4 overflow-x-hidden"
      onSubmit={handleSubmit(
        async (data) => {
          await onSubmit(data, selectedImage, removeImage);
        },
        () => {
          focusFirstInvalidField();
        },
      )}
    >
      <div className={GRID_CLASS}>
        <div className={CELL_CLASS}>
          <ValidatedField label="Course Code" state={codeState}>
            <Input
              id="course-code"
              value={courseCode ?? "Generating..."}
              readOnly
              disabled
              placeholder="CR0001"
              className={inputClass(codeState)}
            />
          </ValidatedField>
        </div>

        <div className={CELL_CLASS}>
          <ValidatedField
            label="Title"
            required
            state={titleState}
            errorMessage={errors.title?.message}
          >
            <Input
              id="course-title"
              placeholder="Course title"
              className={inputClass(titleState)}
              {...register("title")}
            />
          </ValidatedField>
        </div>
      </div>

      <div className={GRID_CLASS}>
        <div className={CELL_CLASS}>
          <ValidatedField
            label="Tagline"
            state={taglineState}
            errorMessage={errors.tagline?.message}
          >
            <Input
              id="course-tagline"
              placeholder="Course tagline"
              className={inputClass(taglineState)}
              {...register("tagline")}
            />
          </ValidatedField>
        </div>

        <div className={CELL_CLASS}>
          <ValidatedField
            label="Category"
            required
            state={categoryState}
            errorMessage={errors.categoryId?.message}
          >
            <Controller
              control={control}
              name="categoryId"
              render={({ field }) => (
                <AppSelect
                  value={field.value}
                  onValueChange={field.onChange}
                  placeholder="Select Category"
                  options={categoryOptions}
                  triggerClassName={inputClass(categoryState)}
                />
              )}
            />
          </ValidatedField>
        </div>
      </div>

      <div className={GRID_CLASS}>
        <div className={CELL_CLASS}>
          <ValidatedField
            label="Type"
            required
            state={modeState}
            errorMessage={errors.modes?.message}
          >
            <Controller
              control={control}
              name="modes"
              render={({ field }) => (
                <AppSelect
                  value={field.value?.[0]}
                  onValueChange={(value) =>
                    field.onChange(value ? [value] : [])
                  }
                  placeholder="Select course type"
                  options={COURSE_MODES.map((mode) => ({
                    label: formatLevelLabel(mode),
                    value: mode,
                  }))}
                  triggerClassName={inputClass(modeState)}
                />
              )}
            />
          </ValidatedField>
        </div>

        <div className={CELL_CLASS}>
          <ValidatedField
            label="Duration"
            required
            state={durationGroupState}
            errorMessage={durationGroupError}
          >
            <div className="grid min-w-0 grid-cols-[minmax(0,5.5rem)_minmax(0,1fr)] gap-2">
              <Input
                id="course-duration"
                type="number"
                min={1}
                placeholder="Enter duration"
                aria-label="Duration amount"
                className={inputClass(durationState)}
                {...register("duration", { valueAsNumber: true })}
              />
              <Controller
                control={control}
                name="durationType"
                render={({ field }) => (
                  <AppSelect
                    value={field.value}
                    onValueChange={field.onChange}
                    placeholder="Select duration unit"
                    options={COURSE_DURATION_TYPES.map((type) => ({
                      label: formatLevelLabel(type),
                      value: type,
                    }))}
                    triggerClassName={inputClass(durationTypeState)}
                  />
                )}
              />
            </div>
          </ValidatedField>
        </div>
      </div>

      <div className={GRID_CLASS}>
        <div className={CELL_CLASS}>
          <ValidatedField
            label="Level"
            required
            state={levelState}
            errorMessage={errors.level?.message}
          >
            <Controller
              control={control}
              name="level"
              render={({ field }) => (
                <AppSelect
                  value={field.value}
                  onValueChange={field.onChange}
                  placeholder="Select difficulty level"
                  options={COURSE_LEVELS.map((level) => ({
                    label: formatLevelLabel(level),
                    value: level,
                  }))}
                  triggerClassName={inputClass(levelState)}
                />
              )}
            />
          </ValidatedField>
        </div>

        <div className={CELL_CLASS}>
          <ValidatedField
            label="Language"
            required
            state={languageState}
            errorMessage={errors.language?.message}
          >
            <Input
              placeholder="Select language"
              className={inputClass(languageState)}
              {...register("language")}
            />
          </ValidatedField>
        </div>
      </div>

      <div className={GRID_CLASS}>
        <div className={`${CELL_CLASS} md:col-span-2`}>
          <h3 className="text-sm font-semibold text-slate-900">Pricing</h3>
        </div>

        <div className={CELL_CLASS}>
          <ValidatedField
            label="Pricing Type"
            required
            state={pricingTypeState}
            errorMessage={errors.isFree?.message}
          >
            <Controller
              control={control}
              name="isFree"
              render={({ field }) => (
                <AppSelect
                  value={field.value ? "FREE" : "PAID"}
                  onValueChange={handlePricingTypeChange}
                  placeholder="Select pricing type"
                  options={PRICING_TYPE_OPTIONS}
                  triggerClassName={inputClass(pricingTypeState)}
                />
              )}
            />
          </ValidatedField>
        </div>

        <div className={CELL_CLASS}>
          <ValidatedField
            label="Original Price"
            required={!pricesDisabled}
            state={originalPriceState}
            errorMessage={errors.originalPrice?.message}
          >
            <div className="relative">
              {!pricesDisabled ? (
                <span className="pointer-events-none absolute left-3 top-1/2 -translate-y-1/2 text-sm text-slate-500">
                  ₹
                </span>
              ) : null}
              <Input
                type="number"
                min={0}
                step="0.01"
                disabled={pricesDisabled}
                placeholder={pricesDisabled ? "Free course" : "Enter original price"}
                className={`${inputClass(originalPriceState)} ${pricesDisabled ? "" : "pl-7"}`}
                {...register("originalPrice", {
                  valueAsNumber: true,
                  onChange: (event) => {
                    const nextOriginal = Number(event.target.value) || 0;
                    const percent = Number(discountPercentValue) || 0;
                    const nextAmount = Math.round((nextOriginal * percent) / 100 * 100) / 100;
                    setValue("discountAmount", nextAmount, {
                      shouldDirty: true,
                      shouldValidate: true,
                    });
                  },
                })}
              />
            </div>
          </ValidatedField>
        </div>
      </div>

      <div className={GRID_CLASS}>
        <div className={CELL_CLASS}>
          <ValidatedField
            label="Discount %"
            required={!pricesDisabled}
            state={discountPercentState}
            errorMessage={errors.discountPercent?.message}
          >
            <Input
              type="number"
              min={0}
              max={100}
              step="0.01"
              disabled={pricesDisabled}
              placeholder={pricesDisabled ? "Free course" : "Enter discount percent"}
              className={inputClass(discountPercentState)}
              {...register("discountPercent", {
                valueAsNumber: true,
                onChange: (event) => {
                  const percent = Number(event.target.value) || 0;
                  const original = Number(originalPriceValue) || 0;
                  const nextAmount = Math.round((original * percent) / 100 * 100) / 100;
                  setValue("discountAmount", nextAmount, {
                    shouldDirty: true,
                    shouldValidate: true,
                  });
                },
              })}
            />
          </ValidatedField>
        </div>

        <div className={CELL_CLASS}>
          <ValidatedField
            label="Discount Amount"
            required={!pricesDisabled}
            state={discountAmountState}
            errorMessage={errors.discountAmount?.message}
          >
            <div className="relative">
              {!pricesDisabled ? (
                <span className="pointer-events-none absolute left-3 top-1/2 -translate-y-1/2 text-sm text-slate-500">
                  ₹
                </span>
              ) : null}
              <Input
                type="number"
                min={0}
                step="0.01"
                disabled={pricesDisabled}
                placeholder={
                  pricesDisabled ? "Free course" : "Enter discount amount"
                }
                className={`${inputClass(discountAmountState)} ${pricesDisabled ? "" : "pl-7"}`}
                {...register("discountAmount", {
                  valueAsNumber: true,
                  onChange: (event) => {
                    const amount = Number(event.target.value) || 0;
                    const original = Number(originalPriceValue) || 0;
                    const nextPercent =
                      original > 0
                        ? Math.round((amount / original) * 10000) / 100
                        : 0;
                    setValue("discountPercent", nextPercent, {
                      shouldDirty: true,
                      shouldValidate: true,
                    });
                  },
                })}
              />
            </div>
          </ValidatedField>
        </div>

        <div className={CELL_CLASS}>
          <ValidatedField label="Final Price" state="neutral">
            <Input
              value={
                pricesDisabled
                  ? "Free"
                  : `₹${computedPricing.discountedPrice.toLocaleString("en-IN", {
                      minimumFractionDigits: 2,
                      maximumFractionDigits: 2,
                    })}`
              }
              readOnly
              disabled
              className={inputClass("neutral")}
            />
          </ValidatedField>
        </div>

        {isEdit && defaultValues?.status ? (
          <div className={CELL_CLASS}>
            <ValidatedField label="Status" state="neutral">
              <Input
                value={defaultValues.status}
                readOnly
                disabled
                className={inputClass("neutral")}
              />
            </ValidatedField>
          </div>
        ) : (
          <div className="hidden min-w-0 md:block" aria-hidden />
        )}

        <input type="hidden" {...register("currency")} />
      </div>

      <ValidatedField
        label="Short Description"
        state={shortDescriptionState}
        errorMessage={errors.shortDescription?.message}
      >
        <Textarea
          id="course-short-description"
          rows={3}
          placeholder="Write a short description of the course..."
          className={inputClass(shortDescriptionState)}
          value={shortDescriptionValue ?? ""}
          onChange={(event) => {
            const next = truncateToMaxWords(
              event.target.value,
              COURSE_WORD_LIMITS.shortDescription,
            );
            setValue("shortDescription", next, {
              shouldDirty: true,
              shouldTouch: true,
              shouldValidate: true,
            });
          }}
          onBlur={register("shortDescription").onBlur}
        />
        <WordCount
          value={shortDescriptionValue ?? ""}
          maxWords={COURSE_WORD_LIMITS.shortDescription}
        />
      </ValidatedField>

      <ValidatedField
        label="Description"
        state={descriptionState}
        errorMessage={errors.description?.message}
      >
        <Textarea
          id="course-description"
          rows={4}
          placeholder="Describe the course, learning outcomes, and what students will learn..."
          className={inputClass(descriptionState)}
          value={descriptionValue ?? ""}
          onChange={(event) => {
            const next = truncateToMaxWords(
              event.target.value,
              COURSE_WORD_LIMITS.description,
            );
            setValue("description", next, {
              shouldDirty: true,
              shouldTouch: true,
              shouldValidate: true,
            });
          }}
          onBlur={register("description").onBlur}
        />
        <WordCount
          value={descriptionValue ?? ""}
          maxWords={COURSE_WORD_LIMITS.description}
        />
      </ValidatedField>

      <ValidatedField
        label="Course Image"
        state={imageState}
        errorMessage={imageError ?? undefined}
      >
        <ImageUploadField
          previewUrl={
            removeImage ? null : (defaultValues?.thumbnailUrl ?? null)
          }
          file={selectedImage}
          disabled={isLoading}
          isUploading={isUploadingImage}
          error={imageError}
          state={imageState}
          onFileSelect={handleImageSelect}
          onRemove={() => {
            setImageTouched(true);
            setSelectedImage(null);
            setRemoveImage(true);
            setImageError(null);
          }}
          validateFile={validateCourseImageFile}
        />
      </ValidatedField>

      <div className="space-y-4 border-t border-slate-200 pt-4">
        <h3 className="text-sm font-semibold text-slate-900">
          SEO / Meta Information
        </h3>

        <CourseMetaField
          label="Meta Title"
          state={metaTitleState}
          errorMessage={errors.metaTitle?.message}
          showReset={!isMetaAuto("metaTitle")}
          onReset={() => resetMetaField("metaTitle")}
        >
          <Input
            placeholder="Enter meta title"
            className={inputClass(metaTitleState)}
            name={metaTitleRegister.name}
            ref={metaTitleRegister.ref}
            onBlur={metaTitleRegister.onBlur}
            onChange={(event) => {
              markMetaManual("metaTitle");
              void metaTitleRegister.onChange(event);
            }}
          />
        </CourseMetaField>

        <CourseMetaField
          label="Meta Description"
          state={metaDescriptionState}
          errorMessage={errors.metaDescription?.message}
          showReset={!isMetaAuto("metaDescription")}
          onReset={() => resetMetaField("metaDescription")}
          multiline
        >
          <Textarea
            rows={3}
            placeholder="Enter meta description"
            className={inputClass(metaDescriptionState)}
            name={metaDescriptionRegister.name}
            ref={metaDescriptionRegister.ref}
            onBlur={metaDescriptionRegister.onBlur}
            onChange={(event) => {
              markMetaManual("metaDescription");
              void metaDescriptionRegister.onChange(event);
            }}
          />
        </CourseMetaField>

        <div className={GRID_CLASS}>
          <div className={CELL_CLASS}>
            <CourseMetaField
              label="Slug"
              state={slugState}
              errorMessage={errors.slug?.message}
              showReset={!isMetaAuto("slug")}
              onReset={() => resetMetaField("slug")}
            >
              <Input
                placeholder="course-slug"
                className={inputClass(slugState)}
                name={slugRegister.name}
                ref={slugRegister.ref}
                onBlur={slugRegister.onBlur}
                onChange={(event) => {
                  markMetaManual("slug");
                  void slugRegister.onChange(event);
                }}
              />
            </CourseMetaField>
          </div>

          <div className={CELL_CLASS}>
            <CourseMetaField
              label="Meta Keywords"
              state={metaKeywordsState}
              errorMessage={errors.metaKeywords?.message}
              showReset={!isMetaAuto("metaKeywords")}
              onReset={() => resetMetaField("metaKeywords")}
            >
              <Input
                placeholder="Enter keywords separated by commas"
                className={inputClass(metaKeywordsState)}
                name={metaKeywordsRegister.name}
                ref={metaKeywordsRegister.ref}
                onBlur={metaKeywordsRegister.onBlur}
                onChange={(event) => {
                  markMetaManual("metaKeywords");
                  void metaKeywordsRegister.onChange(event);
                }}
              />
            </CourseMetaField>
          </div>
        </div>
      </div>

      <div className="flex justify-end gap-2 border-t border-slate-200 pt-4">
        {onCancel ? (
          <Button
            type="button"
            variant="outline"
            disabled={isLoading || isUploadingImage}
            onClick={onCancel}
          >
            Cancel
          </Button>
        ) : null}
        <Button
          type="submit"
          loading={isLoading || isUploadingImage}
          disabled={isLoading || isUploadingImage}
        >
          {isLoading || isUploadingImage ? loadingLabel : submitLabel}
        </Button>
      </div>
    </form>
  );
}
