-- AlterEnum
ALTER TYPE "JobStatus" ADD VALUE IF NOT EXISTS 'PENDING_APPROVAL';
ALTER TYPE "JobStatus" ADD VALUE IF NOT EXISTS 'REJECTED';

-- CreateEnum
CREATE TYPE "JobSource" AS ENUM ('ADMIN', 'COMPANY_ONBOARDING');
CREATE TYPE "JobWorkMode" AS ENUM ('ONSITE', 'REMOTE', 'HYBRID');

-- AlterTable
ALTER TABLE "Job" ALTER COLUMN "jobNumber" DROP NOT NULL;

ALTER TABLE "Job" ADD COLUMN IF NOT EXISTS "source" "JobSource" NOT NULL DEFAULT 'ADMIN';
ALTER TABLE "Job" ADD COLUMN IF NOT EXISTS "companyEmail" TEXT;
ALTER TABLE "Job" ADD COLUMN IF NOT EXISTS "companyPhone" TEXT;
ALTER TABLE "Job" ADD COLUMN IF NOT EXISTS "workMode" "JobWorkMode" NOT NULL DEFAULT 'ONSITE';
ALTER TABLE "Job" ADD COLUMN IF NOT EXISTS "category" TEXT;
ALTER TABLE "Job" ADD COLUMN IF NOT EXISTS "department" TEXT;
ALTER TABLE "Job" ADD COLUMN IF NOT EXISTS "preferredSkills" TEXT[] DEFAULT ARRAY[]::TEXT[];
ALTER TABLE "Job" ADD COLUMN IF NOT EXISTS "qualifications" TEXT[] DEFAULT ARRAY[]::TEXT[];
ALTER TABLE "Job" ADD COLUMN IF NOT EXISTS "benefits" TEXT;
ALTER TABLE "Job" ADD COLUMN IF NOT EXISTS "rejectionReason" TEXT;
ALTER TABLE "Job" ADD COLUMN IF NOT EXISTS "reviewedAt" TIMESTAMP(3);
ALTER TABLE "Job" ADD COLUMN IF NOT EXISTS "reviewedBy" TEXT;

UPDATE "Job" SET "workMode" = 'REMOTE' WHERE "isRemote" = true AND "workMode" = 'ONSITE';

CREATE INDEX IF NOT EXISTS "Job_source_idx" ON "Job"("source");
