export const STUDENT_TOKENS = {
  STUDENT_REPOSITORY: Symbol('STUDENT_REPOSITORY'),
  STUDENT_DOCUMENT_REPOSITORY: Symbol('STUDENT_DOCUMENT_REPOSITORY'),
  RESOLVE_AUTHENTICATED_STUDENT: Symbol(
    'RESOLVE_AUTHENTICATED_STUDENT',
  ),
} as const;
