"use client";

import { Pencil } from "lucide-react";

import { Button } from "@/src/shared/components/ui/button";
import { BatchStatusBadge } from "@/src/features/batches/components/BatchStatusBadge";
import type { Batch } from "@/src/features/batches/types/batch.types";
import {
  formatBatchDuration,
  formatBatchDurationType,
} from "@/src/features/batches/utils/batch-duration.utils";
import { getBatchPricing } from "@/src/features/batches/utils/batch-pricing.util";
import { formatBatchOverviewDate } from "@/src/features/batches/utils/batch-progress.utils";
import { formatBatchMode } from "@/src/features/batches/utils/batch.helper";

import {
  BatchManageField,
  BatchManageSection,
} from "./batch-manage-section";

interface Props {
  batch: Batch;
  onEdit: () => void;
  editDisabled?: boolean;
}

export function BatchManageDetailsPanel({
  batch,
  onEdit,
  editDisabled = false,
}: Props) {
  const isArchived = Boolean(batch.deletedAt || batch.isDeleted);
  const pricing = getBatchPricing(batch);

  return (
    <BatchManageSection
      title="Batch Details"
      description="Batch number is generated by the system and cannot be edited."
      action={
        <Button
          type="button"
          variant="outline"
          size="sm"
          disabled={editDisabled || isArchived}
          onClick={onEdit}
          className="h-9"
        >
          <Pencil className="mr-1.5 h-4 w-4 shrink-0" />
          Edit Batch
        </Button>
      }
    >
      <dl className="grid min-w-0 gap-4 sm:grid-cols-2 lg:grid-cols-3">
        <BatchManageField label="Batch Name" value={batch.name} />
        <BatchManageField label="Batch Number" value={batch.code} />
        <BatchManageField
          label="Course"
          value={batch.course?.title?.trim() || "No course assigned"}
        />
        <BatchManageField
          label="Learning Mode"
          value={formatBatchMode(batch.mode)}
        />
        <BatchManageField
          label="Duration"
          value={formatBatchDuration(batch)}
        />
        <BatchManageField
          label="Duration Type"
          value={formatBatchDurationType(batch)}
        />
        <BatchManageField
          label="Start Date"
          value={formatBatchOverviewDate(batch.startDate)}
        />
        <BatchManageField
          label="End Date"
          value={formatBatchOverviewDate(batch.endDate)}
        />
        <BatchManageField
          label="Status"
          value={
            <BatchStatusBadge
              status={batch.status}
              isActive={batch.isActive}
              isDeleted={isArchived}
              startDate={batch.startDate}
              endDate={batch.endDate}
            />
          }
        />
        <BatchManageField
          label="Original Price"
          value={formatMoney(pricing.originalPrice, pricing.currency)}
        />
        <BatchManageField
          label="Discount Amount"
          value={formatMoney(pricing.discountAmount, pricing.currency)}
        />
        <BatchManageField
          label="Discount Percentage"
          value={`${pricing.discountPercent}%`}
        />
        <BatchManageField
          label="Final Amount"
          value={
            pricing.isFree
              ? "Free"
              : formatMoney(pricing.discountedPrice, pricing.currency)
          }
        />
      </dl>
    </BatchManageSection>
  );
}

function formatMoney(value: number, currency: string): string {
  return new Intl.NumberFormat("en-IN", {
    style: "currency",
    currency,
    maximumFractionDigits: 2,
  }).format(value);
}
