export const COURSE_MODULE_CONSTANTS =
  Object.freeze({
    DEFAULT_POSITION: 1,

    MAX_TITLE_LENGTH: 150,

    MAX_DESCRIPTION_LENGTH: 1000,

    MAX_KEY_SKILLS: 30,

    MAX_KEY_SKILL_LENGTH: 100,

    DEFAULT_INCLUDE_DELETED: false,
  });