export const UPLOADS_TOKENS = {
  UPLOAD_REPOSITORY: Symbol('UPLOAD_REPOSITORY'),
  AWS_S3_SERVICE: Symbol('AWS_S3_SERVICE'),
  IMAGE_PROCESSOR: Symbol('IMAGE_PROCESSOR'),
  UPLOAD_CONFIG: Symbol('UPLOAD_CONFIG'),
} as const;
