"use client";

import { useCallback, useEffect, useRef, useState } from "react";

import Image from "next/image";
import { Controller, useForm } from "react-hook-form";
import { zodResolver } from "@hookform/resolvers/zod";
import { FileText, User, type LucideIcon } from "lucide-react";

import { Input } from "@/src/shared/components/ui/input";
import { Textarea } from "@/src/shared/components/ui/textarea";
import { Button } from "@/src/shared/components/ui/button";
import { AppSelect } from "@/src/shared/components/ui/select";
import { ImageUploadField } from "@/src/shared/components/ui/image-upload-field";
import {
  IconValidatedField,
  iconDecorInputClass,
  ValidatedField,
  validatedFieldInputClass,
  type FieldVisualState,
} from "@/src/shared/components/ui/validated-field";
import { cn } from "@/src/shared/lib/cn";

import { JobTagInput } from "@/src/features/jobs/components/JobTagInput";
import { categoryService } from "@/src/features/categories/services/category.service";

import {
  defaultFinanceNewsFormValues,
  financeNewsFormSchema,
  type FinanceNewsFormValues,
} from "@/src/features/finance-news/schemas/finance-news.schema";
import {
  FINANCE_ARTICLE_AUTHOR_IMAGE_PATH,
  FINANCE_ARTICLE_STATUS_LABELS,
  FINANCE_ARTICLE_STATUSES,
  SHORT_DESCRIPTION_MAX_CHARS,
} from "@/src/features/finance-news/constants/finance-news.constants";
import type { FinanceNewsFormFieldErrors } from "@/src/features/finance-news/utils/finance-news-form-errors";
import type { FinanceNewsUploadFiles } from "@/src/features/finance-news/hooks/use-create-finance-news";
import {
  generateFinanceNewsMeta,
  isAutoGeneratedValue,
} from "@/src/features/finance-news/utils/finance-news-meta.utils";
import { formatFinanceNewsDateTime } from "@/src/features/finance-news/utils/finance-news-display.utils";

type MetaFieldKey = "metaTitle" | "metaDescription" | "metaKeywords";

const MAX_IMAGE_BYTES = 5 * 1024 * 1024;
const ACCEPTED_TYPES = [
  "image/jpeg",
  "image/png",
  "image/webp",
];

const GRID_CLASS =
  "grid w-full min-w-0 grid-cols-1 gap-x-4 gap-y-3 md:grid-cols-2";

function SectionTitle({ children }: { children: string }) {
  return (
    <h3 className="border-b border-[#E8F1FF] pb-1.5 text-xs font-semibold uppercase tracking-wide text-[#2563EB]">
      {children}
    </h3>
  );
}

function getFieldState(
  error?: string,
  value?: string,
): FieldVisualState {
  if (error) {
    return "invalid";
  }

  if (value?.trim()) {
    return "valid";
  }

  return "neutral";
}

function validateImageFile(file: File): string | null {
  if (!ACCEPTED_TYPES.includes(file.type)) {
    return "Only PNG, JPG, JPEG, and WEBP images are allowed";
  }

  if (file.size > MAX_IMAGE_BYTES) {
    return "Image must be 5 MB or smaller";
  }

  return null;
}

function truncateToMaxChars(value: string, maxChars: number): string {
  if (value.length <= maxChars) {
    return value;
  }

  return value.slice(0, maxChars);
}

function CharacterCount({
  value,
  maxChars,
}: {
  value: string;
  maxChars: number;
}) {
  const charCount = value.length;
  const isNearLimit = charCount >= maxChars * 0.9;

  return (
    <p
      className={cn(
        "mt-1 text-right text-xs tabular-nums",
        charCount >= maxChars
          ? "text-red-600"
          : isNearLimit
            ? "text-amber-600"
            : "text-slate-500",
      )}
      aria-live="polite"
    >
      {charCount}/{maxChars} characters
    </p>
  );
}

interface Props {
  formId?: string;
  mode: "create" | "edit";
  initialValues?: FinanceNewsFormValues;
  thumbnailPreviewUrl?: string | null;
  bannerPreviewUrl?: string | null;
  isSubmitting?: boolean;
  externalErrors?: FinanceNewsFormFieldErrors;
  onSubmit: (
    values: FinanceNewsFormValues,
    files: FinanceNewsUploadFiles,
  ) => Promise<void>;
  onCancel?: () => void;
  publishedAt?: string | null;
}

export function FinanceNewsForm({
  formId = "finance-news-form",
  mode,
  initialValues,
  thumbnailPreviewUrl,
  bannerPreviewUrl,
  isSubmitting = false,
  externalErrors = {},
  onSubmit,
  onCancel,
  publishedAt = null,
}: Props) {
  const [categories, setCategories] = useState<
    { id: string; name: string }[]
  >([]);
  const [categoriesLoading, setCategoriesLoading] = useState(true);
  const [thumbnailFile, setThumbnailFile] = useState<File | null>(null);
  const [bannerFile, setBannerFile] = useState<File | null>(null);
  const [thumbnailPreview, setThumbnailPreview] = useState<string | null>(
    thumbnailPreviewUrl ?? null,
  );
  const [bannerPreview, setBannerPreview] = useState<string | null>(
    bannerPreviewUrl ?? null,
  );
  const [thumbnailError, setThumbnailError] = useState<string | null>(null);
  const [bannerError, setBannerError] = useState<string | null>(null);
  const [thumbnailRemoved, setThumbnailRemoved] = useState(false);
  const [bannerRemoved, setBannerRemoved] = useState(false);

  const {
    control,
    register,
    handleSubmit,
    watch,
    setValue,
    reset,
    formState: { errors },
  } = useForm<FinanceNewsFormValues>({
    resolver: zodResolver(financeNewsFormSchema),
    defaultValues: initialValues ?? defaultFinanceNewsFormValues,
  });

  const metaAutoRef = useRef<Record<MetaFieldKey, boolean>>({
    metaTitle: mode === "create",
    metaDescription: mode === "create",
    metaKeywords: mode === "create",
  });

  const titleValue = watch("title") ?? "";
  const shortDescription = watch("shortDescription") ?? "";
  const contentValue = watch("content") ?? "";
  const tagsValue = watch("tags") ?? [];
  const statusValue = watch("status");

  const getMetaSource = useCallback(
    () => ({
      title: titleValue,
      shortDescription,
      content: contentValue,
      tags: tagsValue,
    }),
    [contentValue, shortDescription, tagsValue, titleValue],
  );

  const syncMetaAutoFlags = useCallback((values?: Partial<FinanceNewsFormValues>) => {
    const generated = generateFinanceNewsMeta({
      title: values?.title ?? "",
      shortDescription: values?.shortDescription ?? "",
      content: values?.content ?? "",
      tags: values?.tags ?? [],
    });

    metaAutoRef.current = {
      metaTitle: isAutoGeneratedValue(values?.metaTitle, generated.metaTitle),
      metaDescription: isAutoGeneratedValue(
        values?.metaDescription,
        generated.metaDescription,
      ),
      metaKeywords: isAutoGeneratedValue(
        values?.metaKeywords,
        generated.metaKeywords,
      ),
    };
  }, []);

  useEffect(() => {
    const merged = {
      ...defaultFinanceNewsFormValues,
      ...initialValues,
    };
    reset(merged);
    syncMetaAutoFlags(merged);
  }, [initialValues, mode, reset, syncMetaAutoFlags]);

  useEffect(() => {
    const generated = generateFinanceNewsMeta(getMetaSource());

    if (metaAutoRef.current.metaTitle) {
      setValue("metaTitle", generated.metaTitle);
    }
    if (metaAutoRef.current.metaDescription) {
      setValue("metaDescription", generated.metaDescription);
    }
    if (metaAutoRef.current.metaKeywords) {
      setValue("metaKeywords", generated.metaKeywords);
    }
  }, [getMetaSource, setValue, titleValue, shortDescription, contentValue, tagsValue]);

  const markMetaManual = (field: MetaFieldKey) => {
    metaAutoRef.current[field] = false;
  };

  const metaTitleRegister = register("metaTitle");
  const metaDescriptionRegister = register("metaDescription");
  const metaKeywordsRegister = register("metaKeywords");

  const publishedOnLabel =
    statusValue === "PUBLISHED" && publishedAt
      ? formatFinanceNewsDateTime(publishedAt)
      : statusValue === "PUBLISHED" && mode === "create"
        ? "Set automatically when you publish"
        : "—";

  useEffect(() => {
    let cancelled = false;

    const loadCategories = async () => {
      try {
        setCategoriesLoading(true);
        const response = await categoryService.getCategories({
          search: "",
          page: 1,
          pageSize: 100,
          status: "ACTIVE",
        });
        if (!cancelled) {
          setCategories(
            response.data.map((category) => ({
              id: category.id,
              name: category.name,
            })),
          );
        }
      } catch {
        if (!cancelled) {
          setCategories([]);
        }
      } finally {
        if (!cancelled) {
          setCategoriesLoading(false);
        }
      }
    };

    void loadCategories();

    return () => {
      cancelled = true;
    };
  }, []);

  useEffect(() => {
    setThumbnailPreview(thumbnailPreviewUrl ?? null);
    setThumbnailFile(null);
    setThumbnailRemoved(false);
    setThumbnailError(null);
  }, [thumbnailPreviewUrl]);

  useEffect(() => {
    setBannerPreview(bannerPreviewUrl ?? null);
    setBannerFile(null);
    setBannerRemoved(false);
    setBannerError(null);
  }, [bannerPreviewUrl]);

  const mergedErrors = {
    title: errors.title?.message ?? externalErrors.title,
    shortDescription:
      errors.shortDescription?.message ?? externalErrors.shortDescription,
    content: errors.content?.message ?? externalErrors.content,
    categoryId: errors.categoryId?.message ?? externalErrors.categoryId,
    authorName: errors.authorName?.message ?? externalErrors.authorName,
    metaTitle: errors.metaTitle?.message ?? externalErrors.metaTitle,
    metaDescription:
      errors.metaDescription?.message ?? externalErrors.metaDescription,
    metaKeywords: errors.metaKeywords?.message ?? externalErrors.metaKeywords,
    tags: errors.tags?.message ?? externalErrors.tags,
    status: errors.status?.message ?? externalErrors.status,
  };

  const submitHandler = handleSubmit(async (values) => {
    await onSubmit(values, {
      thumbnail: thumbnailFile,
      banner: bannerFile,
      removeThumbnail: thumbnailRemoved,
      removeBanner: bannerRemoved,
    });
  });

  return (
    <form id={formId} onSubmit={submitHandler} className="space-y-5">
      {externalErrors.root ? (
        <div className="rounded-lg border border-red-200 bg-red-50 px-3 py-2 text-sm text-red-700">
          {externalErrors.root}
        </div>
      ) : null}

      <SectionTitle>Article Details</SectionTitle>

      <IconValidatedField
        label="Title"
        required
        icon={FileText}
        state={getFieldState(mergedErrors.title, titleValue)}
        errorMessage={mergedErrors.title}
      >
        <Input
          {...register("title")}
          disabled={isSubmitting}
          className={iconDecorInputClass(
            getFieldState(mergedErrors.title, titleValue),
            "w-full",
          )}
          placeholder="Enter article title"
        />
        <p className="mt-1 text-xs text-[#647A9B]">
          URL slug is generated automatically from the title.
        </p>
      </IconValidatedField>

      <ValidatedField
        label="Short Description"
        state={getFieldState(
          mergedErrors.shortDescription,
          shortDescription,
        )}
        errorMessage={mergedErrors.shortDescription}
      >
        <Controller
          control={control}
          name="shortDescription"
          render={({ field }) => (
            <Textarea
              value={field.value ?? ""}
              disabled={isSubmitting}
              rows={3}
              className={validatedFieldInputClass(
                getFieldState(
                  mergedErrors.shortDescription,
                  field.value ?? "",
                ),
                "w-full resize-y",
              )}
              placeholder="Brief summary for listings and previews"
              onBlur={field.onBlur}
              onChange={(event) => {
                field.onChange(
                  truncateToMaxChars(
                    event.target.value,
                    SHORT_DESCRIPTION_MAX_CHARS,
                  ),
                );
              }}
            />
          )}
        />
        <CharacterCount
          value={shortDescription}
          maxChars={SHORT_DESCRIPTION_MAX_CHARS}
        />
      </ValidatedField>

      <ValidatedField
        label="Content"
        required
        state={getFieldState(mergedErrors.content, watch("content"))}
        errorMessage={mergedErrors.content}
      >
        <Textarea
          {...register("content")}
          disabled={isSubmitting}
          rows={10}
          className={validatedFieldInputClass(
            getFieldState(mergedErrors.content, watch("content")),
            "w-full resize-y font-mono text-sm",
          )}
          placeholder="Write the full article content"
        />
      </ValidatedField>

      <SectionTitle>Meta / SEO</SectionTitle>

      <div className={GRID_CLASS}>
        <ValidatedField
          label="Meta Title"
          state={getFieldState(mergedErrors.metaTitle, watch("metaTitle"))}
          errorMessage={mergedErrors.metaTitle}
        >
          <Input
            name={metaTitleRegister.name}
            ref={metaTitleRegister.ref}
            onBlur={metaTitleRegister.onBlur}
            disabled={isSubmitting}
            className={validatedFieldInputClass(
              getFieldState(mergedErrors.metaTitle, watch("metaTitle")),
            )}
            placeholder="SEO title"
            onChange={(event) => {
              markMetaManual("metaTitle");
              void metaTitleRegister.onChange(event);
            }}
          />
        </ValidatedField>

        <ValidatedField
          label="Meta Keywords"
          state={getFieldState(mergedErrors.metaKeywords, watch("metaKeywords"))}
          errorMessage={mergedErrors.metaKeywords}
        >
          <Input
            name={metaKeywordsRegister.name}
            ref={metaKeywordsRegister.ref}
            onBlur={metaKeywordsRegister.onBlur}
            disabled={isSubmitting}
            className={validatedFieldInputClass(
              getFieldState(mergedErrors.metaKeywords, watch("metaKeywords")),
            )}
            placeholder="keyword-one, keyword-two"
            onChange={(event) => {
              markMetaManual("metaKeywords");
              void metaKeywordsRegister.onChange(event);
            }}
          />
        </ValidatedField>
      </div>

      <ValidatedField
        label="Meta Description"
        state={getFieldState(
          mergedErrors.metaDescription,
          watch("metaDescription"),
        )}
        errorMessage={mergedErrors.metaDescription}
      >
        <Textarea
          name={metaDescriptionRegister.name}
          ref={metaDescriptionRegister.ref}
          onBlur={metaDescriptionRegister.onBlur}
          disabled={isSubmitting}
          rows={3}
          className={validatedFieldInputClass(
            getFieldState(
              mergedErrors.metaDescription,
              watch("metaDescription"),
            ),
            "w-full resize-y",
          )}
          placeholder="SEO description"
          onChange={(event) => {
            markMetaManual("metaDescription");
            void metaDescriptionRegister.onChange(event);
          }}
        />
      </ValidatedField>

      <SectionTitle>Classification</SectionTitle>

      <div className={GRID_CLASS}>
        <ValidatedField
          label="Category"
          required
          select
          state={getFieldState(mergedErrors.categoryId, watch("categoryId"))}
          errorMessage={mergedErrors.categoryId}
        >
          <Controller
            control={control}
            name="categoryId"
            render={({ field }) => (
              <AppSelect
                value={field.value || undefined}
                disabled={isSubmitting || categoriesLoading}
                triggerClassName={validatedFieldInputClass(
                  getFieldState(mergedErrors.categoryId, field.value),
                  "h-[46px] w-full",
                  { select: true },
                )}
                placeholder={
                  categoriesLoading ? "Loading categories..." : "Select category"
                }
                onValueChange={field.onChange}
                options={categories.map((category) => ({
                  label: category.name,
                  value: category.id,
                }))}
              />
            )}
          />
        </ValidatedField>

        <ValidatedField
          label="Publish Status"
          required
          select
          state={getFieldState(mergedErrors.status, watch("status"))}
          errorMessage={mergedErrors.status}
        >
          <Controller
            control={control}
            name="status"
            render={({ field }) => (
              <AppSelect
                value={field.value}
                disabled={isSubmitting}
                placeholder="Select publish status"
                triggerClassName={validatedFieldInputClass(
                  getFieldState(mergedErrors.status, field.value),
                  "h-[46px] w-full",
                  { select: true },
                )}
                onValueChange={field.onChange}
                options={FINANCE_ARTICLE_STATUSES.map((status) => ({
                  label: FINANCE_ARTICLE_STATUS_LABELS[status],
                  value: status,
                }))}
              />
            )}
          />
        </ValidatedField>

        <ValidatedField label="Published On" state="neutral">
          <Input
            readOnly
            disabled
            value={publishedOnLabel}
            className={validatedFieldInputClass("neutral")}
          />
        </ValidatedField>
      </div>

      <ValidatedField
        label="Tags"
        state={getFieldState(mergedErrors.tags, watch("tags")?.join(", "))}
        errorMessage={mergedErrors.tags}
      >
        <Controller
          control={control}
          name="tags"
          render={({ field }) => (
            <JobTagInput
              values={field.value ?? []}
              disabled={isSubmitting}
              placeholder="Type a tag and press Enter"
              state={getFieldState(
                mergedErrors.tags,
                field.value?.join(", "),
              )}
              onChange={field.onChange}
            />
          )}
        />
      </ValidatedField>

      <SectionTitle>Author</SectionTitle>

      <div className={GRID_CLASS}>
        <IconValidatedField
          label="Author Name"
          icon={User}
          state={getFieldState(mergedErrors.authorName, watch("authorName"))}
          errorMessage={mergedErrors.authorName}
        >
          <Input
            {...register("authorName")}
            disabled={isSubmitting}
            className={iconDecorInputClass(
              getFieldState(mergedErrors.authorName, watch("authorName")),
              "w-full",
            )}
            placeholder="MCJ Team"
          />
        </IconValidatedField>

        <ValidatedField label="Author Image" state="neutral">
          <div className="flex h-[46px] items-center gap-3 rounded-xl border border-[#DCE8F5] bg-white px-3">
            <Image
              src={FINANCE_ARTICLE_AUTHOR_IMAGE_PATH}
              alt="MCJ"
              width={32}
              height={32}
              className="h-8 w-8 rounded-md object-contain"
            />
            <span className="text-sm text-[#647A9B]">MCJ logo (default)</span>
          </div>
        </ValidatedField>
      </div>

      <SectionTitle>Media</SectionTitle>

      <div className={GRID_CLASS}>
        <ValidatedField
          label="Thumbnail"
          state={thumbnailError || externalErrors.thumbnail ? "invalid" : "neutral"}
          errorMessage={thumbnailError ?? externalErrors.thumbnail}
        >
          <ImageUploadField
            previewUrl={thumbnailPreview}
            file={thumbnailFile}
            disabled={isSubmitting}
            entityLabel="thumbnail"
            previewAlt="Article thumbnail preview"
            compact
            validateFile={validateImageFile}
            onFileSelect={(file) => {
              if (!file) {
                return;
              }
              const validationError = validateImageFile(file);
              if (validationError) {
                setThumbnailError(validationError);
                return;
              }
              setThumbnailError(null);
              setThumbnailRemoved(false);
              setThumbnailFile(file);
            }}
            onRemove={() => {
              setThumbnailFile(null);
              setThumbnailPreview(null);
              setThumbnailError(null);
              setThumbnailRemoved(true);
            }}
          />
        </ValidatedField>

        <ValidatedField
          label="Banner"
          state={bannerError || externalErrors.banner ? "invalid" : "neutral"}
          errorMessage={bannerError ?? externalErrors.banner}
        >
          <ImageUploadField
            previewUrl={bannerPreview}
            file={bannerFile}
            disabled={isSubmitting}
            entityLabel="banner"
            previewAlt="Article banner preview"
            validateFile={validateImageFile}
            onFileSelect={(file) => {
              if (!file) {
                return;
              }
              const validationError = validateImageFile(file);
              if (validationError) {
                setBannerError(validationError);
                return;
              }
              setBannerError(null);
              setBannerRemoved(false);
              setBannerFile(file);
            }}
            onRemove={() => {
              setBannerFile(null);
              setBannerPreview(null);
              setBannerError(null);
              setBannerRemoved(true);
            }}
          />
        </ValidatedField>
      </div>

      <div className="flex flex-col-reverse gap-2 border-t border-[#E8F1FF] pt-4 sm:flex-row sm:justify-end">
        {onCancel ? (
          <Button
            type="button"
            variant="outline"
            disabled={isSubmitting}
            onClick={onCancel}
          >
            Cancel
          </Button>
        ) : null}

        <Button
          type="submit"
          disabled={isSubmitting}
          className="border-0 bg-gradient-to-r from-[#0EA5E9] to-[#2563EB] px-6 text-sm font-semibold text-white"
        >
          {isSubmitting
            ? mode === "create"
              ? "Creating..."
              : "Saving..."
            : mode === "create"
              ? "Create Article"
              : "Save Changes"}
        </Button>
      </div>
    </form>
  );
}
