export const AUTH_TOKENS = {
  USER_REPOSITORY: 'USER_REPOSITORY',
  SESSION_REPOSITORY: 'SESSION_REPOSITORY',
  AUDIT_LOG_REPOSITORY: 'AUDIT_LOG_REPOSITORY',
  TOKEN_PORT: 'TOKEN_PORT',
  TOTP_PORT: 'TOTP_PORT',
  PASSWORD_HASHER: 'PASSWORD_HASHER',
  PASSWORD_RESET_REPOSITORY: 'PASSWORD_RESET_REPOSITORY',
  USER_DOMAIN_SERVICE: 'USER_DOMAIN_SERVICE',
  AUTH_RATE_LIMITER: 'AUTH_RATE_LIMITER',
};
