export enum EnrollmentStatus {
  PENDING = 'PENDING',
  PENDING_APPROVAL = 'PENDING_APPROVAL',
  ADVANCED = 'ADVANCED',
  ADMITTED = 'ADMITTED',
  ACTIVE = 'ACTIVE',
  COMPLETED = 'COMPLETED',
  DROPPED = 'DROPPED',
  CANCELLED = 'CANCELLED',
  REJECTED = 'REJECTED',
}
