export enum EnrollmentStatus {
  PENDING = 'PENDING',
  PENDING_APPROVAL = 'PENDING_APPROVAL',
  LEAD = 'LEAD',
  ENROLLED = 'ENROLLED',
  JOINED = 'JOINED',
  ACTIVE = 'ACTIVE',
  COMPLETED = 'COMPLETED',
  DROPPED = 'DROPPED',
  PLACED = 'PLACED',
  CANCELLED = 'CANCELLED',
  REJECTED = 'REJECTED',
}
