export interface CourseMetaSource {
  title?: string;
  tagline?: string;
  shortDescription?: string;
  description?: string;
  categoryName?: string;
  level?: string;
}

export interface GeneratedCourseMeta {
  metaTitle: string;
  metaDescription: string;
  slug: string;
  metaKeywords: string;
}

export function slugifyFromTitle(title: string): string {
  return title
    .trim()
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");
}

export function generateMetaTitle(title: string): string {
  return title.trim().slice(0, 160);
}

export function generateMetaDescription(source: CourseMetaSource): string {
  const short = source.shortDescription?.trim();
  if (short) {
    return short.slice(0, 300);
  }

  const description = source.description?.trim();
  if (description) {
    return description.slice(0, 300);
  }

  const tagline = source.tagline?.trim();
  if (tagline) {
    return tagline.slice(0, 300);
  }

  return "";
}

export function generateMetaKeywords(source: CourseMetaSource): string {
  const tokens = new Set<string>();

  const addTokens = (value?: string) => {
    if (!value?.trim()) {
      return;
    }

    value
      .toLowerCase()
      .split(/[^a-z0-9]+/g)
      .map((token) => token.trim())
      .filter((token) => token.length > 2)
      .forEach((token) => tokens.add(token));
  };

  addTokens(source.title);
  addTokens(source.tagline);
  addTokens(source.shortDescription);
  addTokens(source.categoryName);
  addTokens(source.level);

  return Array.from(tokens).slice(0, 12).join(", ");
}

export function generateCourseMeta(
  source: CourseMetaSource,
): GeneratedCourseMeta {
  const title = source.title?.trim() ?? "";

  return {
    metaTitle: generateMetaTitle(title),
    metaDescription: generateMetaDescription(source),
    slug: slugifyFromTitle(title),
    metaKeywords: generateMetaKeywords(source),
  };
}

export function isAutoGeneratedValue(
  current: string | undefined | null,
  generated: string,
): boolean {
  const normalizedCurrent = (current ?? "").trim();
  const normalizedGenerated = generated.trim();

  if (!normalizedCurrent) {
    return true;
  }

  return normalizedCurrent === normalizedGenerated;
}
